
spring:
  thymeleaf:
    cache: false
  profiles:
    active: default
---
spring:
  profiles: default  
app:
  version: 1.0.9-SNAPSHOT 
  
#overriding embedded server properties
server:
  port: 8082
  context-path: /serviceTester

ssl:
  port: 8443
  
mongodb:
  host: alpmasbuild
  db: mipDev
  
mipScenarios:
  file: mipScenarios.xls
  worksheet: Scenarios
  resultsfile: scenarioResults
  resultsfileext: .xls
  resultslocation: C:\MIPTesting\results\
  sourcelocation: C:\MIPTesting\source\
  
request:
  userid: 83186
  url: http://xx.xx.xx.xxx:xxxxx/xxxxxxxx
  read-timeout: 300000
  connection-timeout: 200000
  
filter:
  default: true
  
logging:
  path: C:\MIPTesting\logs\
  
management:
  context-path: /admin

endpoints:
  health:
    sensitive: false
  
---
spring:
  profiles: qa

server:
  port: 8082
    
mongodb:
  host: alpmasbuild
  db: mipTesting
  
request:
  userid: 83186
  url: http://xx.xx.xx.xxx:xxxxx/xxxxxxxx
  
mipScenarios:
  resultslocation: E:\mas2\tools\MIPTester\results\
  sourcelocation: E:\mas2\tools\MIPTester\source\